// ============================================================================
// MISSION LOG STORAGE ENGINE
// Local-first storage for per-mission summaries generated by inference engine
// ============================================================================

export interface MissionLogEntry {
  lessonId: number;
  lessonTitle: string;
  insightSummary: string;        // Combined operator reflections
  patterns: string[];            // Extracted themes
  traitSignals: string[];        // Mapped to TRAIT_MAP tags
  shadowSignals: string[];       // Shadow tendencies detected
  powerSignals: string[];        // Power tendencies detected
  echelonRead?: string;          // Echelon's own contribution — two minds, one record
  timestamp: number;
}

const KEY = "neuroverse_mission_log_v2";

/**
 * Save a mission log entry to local storage
 */
export function saveMissionLogEntry(entry: MissionLogEntry): void {
  try {
    const existing = getMissionLogs();
    existing.push(entry);
    localStorage.setItem(KEY, JSON.stringify(existing));
    console.log(`[MISSION LOG] Saved entry for lesson ${entry.lessonId}`);
  } catch (error) {
    console.error("[MISSION LOG] Failed to save entry:", error);
  }
}

/**
 * Get all mission logs
 */
export function getMissionLogs(): MissionLogEntry[] {
  try {
    const stored = localStorage.getItem(KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (error) {
    console.error("[MISSION LOG] Failed to load entries:", error);
    return [];
  }
}

/**
 * Attach Echelon's read to an existing mission log entry.
 * The read arrives asynchronously (the operator's own AI writes it after the
 * local inference pass) — update the latest entry for the lesson in place.
 */
export function attachEchelonRead(lessonId: number, read: string): void {
  try {
    const logs = getMissionLogs();
    for (let i = logs.length - 1; i >= 0; i--) {
      if (logs[i].lessonId === lessonId) {
        logs[i].echelonRead = read;
        localStorage.setItem(KEY, JSON.stringify(logs));
        console.log(`[MISSION LOG] Echelon's read attached for lesson ${lessonId}`);
        return;
      }
    }
  } catch (error) {
    console.error("[MISSION LOG] Failed to attach Echelon's read:", error);
  }
}

/**
 * Get mission log for a specific lesson
 */
export function getMissionLog(lessonId: number): MissionLogEntry | null {
  const logs = getMissionLogs();
  return logs.find(log => log.lessonId === lessonId) || null;
}

/**
 * Clear all mission logs (used for reset/debugging)
 */
export function clearMissionLogs(): void {
  try {
    localStorage.removeItem(KEY);
    console.log("[MISSION LOG] Cleared all entries");
  } catch (error) {
    console.error("[MISSION LOG] Failed to clear entries:", error);
  }
}

/**
 * Get mission log count
 */
export function getMissionLogCount(): number {
  return getMissionLogs().length;
}
